_news:
    pattern:  /news
    defaults: { _controller: NewsShowBundle:Default:news }

_login:
    pattern:  /login
    defaults: { _controller: NewsShowBundle:Default:login }

_main:
  pattern: /main
  defaults: {_controller: NewsShowBundle:Default:index}

