parameters:
#    news_show.example.class: Roozbeh\NewsShowBundle\Example

services:
#    news_show.example:
#        class: %news_show.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

