security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

        Roozbeh\NewsShowBundle\Entity\Author:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      chain_provider:
          chain:
              providers: [in_memory, user_db]
      in_memory:
          memory:
              users:
                  roozbeh: { password: 601f1889667efaebb33b8c12572835da3f027f78, roles: [ 'ROLE_ADMIN' ] }

      user_db:
          entity: { class: Roozbeh\NewsShowBundle\Entity\Author, property: username }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
                pattern:    ^/login$
                anonymous:  ~

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   /logout
                target: /main
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


    access_control:
        - { path: ^/write, roles: ROLE_USER }
        - { path: ^/ , roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
